indent_type = "Spaces"
indent_width = 4
column_width = 120
line_endings = "Unix"
quote_style = "AutoPreferSingle"
call_parentheses = "Always"
collapse_simple_statement = "Always"
no_call_parentheses = true
syntax = "LuaJIT"
