return {
    require "config.themes.moonfly",
    require "config.themes.one-dark",
    require "config.themes.catppuccin",
    require "config.themes.kanagawa",
    require "config.themes.neon",
    require "config.themes.everforest",
    require "config.themes.tokyo-night",
    require "config.themes.tokyodark",
    require "config.themes.citruszest",
    require "config.themes.ramojus",
    require "config.themes.dracula",
    require "config.themes.rose",
    require "config.themes.darkvoid",
    require "config.themes.material",
}
