return {
    require'config.themes.nord',
    require'config.themes.moonfly',
    require'config.themes.lackluster',
    require'config.themes.one',
    require'config.themes.catppuccin',
    require'config.themes.kanagawa',
    require'config.themes.neon',
    require'config.themes.everforest',
    require'config.themes.oxocarbon',
    require'config.themes.tokyodark',
    require'config.themes.synthwave',
    require'config.themes.citruszest',
    require'config.themes.ramojus',
}
